### PR TITLE
Fixed RTC1_IRQHandler linking problem.

### PR DESCRIPTION
**Pull request by anangl**
This is an ugly temporary fix. But it works for all 3 toolchains and I think we can use it until we find a final solution to this issue.

### CODE REVIEW

**Comment by anangl** [comment]
For some reason when RTC1_Handler is defined in us_ticker.c it is properly linked (i.e. it overrides weak symbol defined in startup file). But when it was defined in some other file (e.g. os_tick.c, but I tried other names as well) linkers used the weak symbol and linked Default_Handler instead.
My proposition is to use this fix until we find the actual reason of such behaviour of linkers and provide a proper solution.
@0xc0170 can you look at this?

**Comment by anangl** [comment]
I think I know why RTC1_Handler is discarded when it is placed in os_tick.c, and it is not when it is placed in us_ticker.c.
The reason is that no other symbol defined in os_tick.c (RTOS stuff) is used in the test application, so linkers seem to decide to discard whole os_tick.o contents, including RTC1_Handler, though this one is referenced from startup file (apparently weak definition of RTC1_Handler in the same startup file takes precedence). A bit surprising, isn't it?
Hence, including os_tick.c (as os_tick.inc) from us_ticker.c helps in this case. I think the proper solution will be to merge os_tick.c contents into us_ticker.c, since this including is just disgusting.

**Comment by 0xc0170** [comment]
> For some reason when RTC1_Handler is defined in us_ticker.c it is properly linked (i.e. it overrides weak symbol defined in startup file). But when it was defined in some other file (e.g. os_tick.c, but I tried other names as well) linkers used the weak symbol and linked Default_Handler instead.
> My proposition is to use this fix until we find the actual reason of such behaviour of linkers and provide a proper solution.

the us ticker RTC handler should be registered via SetVector(), not used weak attribute. If an app wants to overwrite it, it should follow the same. weak symbols are not friendly with archives, thus for instance startup file is an object file, not part of mbed library archive, or any other files containing weak symbols.

**Comment by pan-** [comment]
Vector relocation is really tricky on nrf51. The real IRQ vector is maintained by the softdevice, **not** by the application, the softdevice just jump to user defined IRQS at an hard-coded address.

The function `sd_softdevice_vector_table_base_set` can be used to relocate the application vector but it can only be used if the binary contain the Nordic bootloader and it is not the case in mbed (for most targets).

I suggest to use this PR (let me test it first ...) for now. 

At the end, the issue is rather in the build system, if it happen for this case it can happen for other code as well.

**Comment by 0xc0170** [comment]
https://github.com/mbedmicro/mbed/blob/master/hal/targets/cmsis/TARGET_NORDIC/TARGET_MCU_NRF51822/cmsis_nvic.c ? There's no softdevice call there? How does this work then?

> At the end, the issue is rather in the build system, if it happen for this case it can happen for other code as well.

yeah, as yotta resolved it - do not use weak symbols :-) And our build system - within mbed lib, using object files for those files that provide weak symbols as part of mbed (mbed_overrides, etc).

**Comment by pan-** [comment]
Everything works for me on GCC.
I can't test for other compiler where I am. 

What should we do @0xc0170 ? 
I would like to carry on with this fix for now.

**Comment by pan-** [comment]
This copy pasta never worked I guess. 
The ram start at 0x20000000 on nrf51. This code try to write at 0x10000000.

**Comment by 0xc0170** [comment]
> The ram start at 0x20000000 on nrf51. This code try to write at 0x10000000.

:sunglasses: 

@pan- Is there a way to not to use weak symbols within mbed lib , means within HAL? I would imagine there's only one RTC handler within mbed and its used by mbed. There shall be a call to overwrite in (in many cases its SetVector/GetVector)

**Comment by pan-** [comment]
The best way to not have to deal with a weak symbol is to not declare it as weak.

@anangl: why is it not possible to declare RTC1_IrqHandler as non weak ?

**Comment by anangl** [comment]
RTC1_IRQHandler is not declared as weak within the mbed lib. The weak declaration is only in the startup file, which is not included in the library, but linked directly.
The problem is that the strong RTC1_IRQHandler from mbed lib is not used by linkers to override the weak one (from startup file) when this strong RTC1_IRQHandler is defined in a source file from which no other symbol is referenced. In such a case linkers do not extract the object for this source file from the library (since they don't need it), and consequently they don't see the strong definition of RTC1_IRQHandler.
It appears to be the standard behavior of linkers - to look in a library only for undefined symbols. And since RTC1_IRQHandler is defined (though it is weak) linkers do not look for it in the mbed lib. The "--whole-archive" switch changes this behavior for GNU linker.

**Comment by pan-** [comment]
@anangl That's plainly understood.

My question is rather, should it be defined as weak in the startup file ? 

https://github.com/pan-/mbed/blob/nrf52_nrf51_unified_integration/hal/targets/cmsis/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TOOLCHAIN_GCC_ARM/startup_NRF51822.S#L253

If this line is removed then RTC1_IRQHandler is not weak anymore in this file and therefore _has to be defined_ somewhere else.

**Comment by anangl** [comment]
> If this line is removed then RTC1_IRQHandler is not weak anymore in this file and therefore has to be defined somewhere else.

Yes, that will work. But I'm not convinced that modyfing startup files (it need to be done for all compilers) is the best way to solve this problem. @nvlsianpu What do you think?

**Comment by pan-** [comment]
Lets continue this discussion latter on, the target of this PR was an hotfix.
Weak symbols handling and interrupt declaration is a system wide problematic.

**Comment by nvlsianpu** [comment]
I agree with you both - we can manage/improve this later if we have enough time. Personally I prefer to have a week handler IRQ in a startupxxx.s - now it is a post scriptum comment.

**Pull request merged**
